Feature branch
Rayan84/Apple-website-webpage-clone pull request #1
Opened 2020-09-01 14:06 UTC by Rayan84

Building with Backgrounds and Gradients

2020-09-01 19:17 UTC, SafaErden requested changes
## Status: Require changes ♻️

**Hi TEAM, your project is awesome and it really looks exactly like the original. 👐 However, we need a little fix before we can proceed. Kindly find comments below**
##

**REQUIRED CHANGES**

- [ ] Your layout causes redundant horizontal scroll, please fix your code to prevent the horizontal scroll bar.
![image](https://user-images.githubusercontent.com/60184961/91894876-010ff680-ec9f-11ea-969e-388eb01800d4.png)

- [ ] Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

So please apply DRY CSS rules to prevent repeating the same rules.

- [ ] The footer contents are aligned center in the original page,

![image](https://user-images.githubusercontent.com/60184961/91895947-c0b17800-eca0-11ea-8e2b-ed81bce59c7b.png)

 But in your project, they are not aligned center.

![image](https://user-images.githubusercontent.com/60184961/91895910-af686b80-eca0-11ea-9807-59f3ea92512e.png)

Please kindly center them.


- [ ] The other required changes are listed below. Please kindly fix them.


##

**NOTES**

Friendly reminder: Remember it's important to have a professional repo so you can increase your job opportunities that's why your pull requests should have a meaningful title and description. Improper and insufficient PR title/description is an invalidation reason. Please take a step back and read the lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

##

**SUMMARY**

As I mentioned above, your project is almost done. You have some minor issues to solve. Please be an optimist and do not forget that the main purpose is to learn and practice. Do not let the requested changes discourage you 👍

##

*Kindly make the changes and submit another code review when you are ready*

Questions or comments? Reach me on [Twitter](https://twitter.com/safaerden) or [LinkedIn](https://www.linkedin.com/in/safaerden/)

Happy coding_ 👨‍💻 

**Safa ERDEN**

2020-09-01 19:17 UTC, SafaErden commented on index.html
> +            <li class="nav-li">Support</li>
- [x] The first eight elements should be links (to other sections or #). So please apply the proper HTML tags to convert these `li` items to links.

2020-09-01 19:17 UTC, SafaErden commented on index.html
> +
- [OPTIONAL] I can suggest you to use a code-formatter to prevent redundant empty lines and indentations to have a neat code.

2020-09-01 19:17 UTC, SafaErden commented on index.html
> +    </section>
- [x] The bottom section contains four elements which are links (to other articles or `#`). So please apply the proper HTML tags to convert these section items to links.

2020-09-01 19:17 UTC, SafaErden commented on index.html
> +      <header>
- [ ] Please consider the use of the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document, so please take the `nav` outside of the `main` tag.

2020-09-01 19:17 UTC, SafaErden commented on README.md
> +* Twitter:[@Rayan65096267]https://twitter.com/Rayan65096267
- [ ] Please fix the improper applied and broken links in your README to make your project look more professional.

2020-09-01 19:17 UTC, SafaErden commented on README.md
> +[Apple-website-webpage-clone] https://ecstatic-lamarr-cd95c7.netlify.app/
- [ ] Please fix the improper applied and broken links in your README to make your project look more professional.

2020-09-01 19:17 UTC, SafaErden commented on README.md
> +* Twitter:[@DIBYEND78120480]
- [ ] Please fix the improper applied and broken links in your README to make your project look more professional.

2020-09-01 19:17 UTC, SafaErden commented on README.md
> +[screenshot](screenshot.PNG)
- [OPTIONAL] You can directly implement the screenshot of your project to your README instead of adding the screenshot's link.

2020-09-02 16:35 UTC, SafaErden requested changes
## Status: Require changes ♻️

**Hi TEAM, it is really nice to see that you have implemented most of the required changes. 👐 However, we need a little fix before we can proceed. Kindly find comments below**
##

**REQUIRED CHANGES**

- [x] Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

Your style repeats some of the CSS rules, so please apply DRY CSS rules to prevent repeating the same rules.

- [ ] The footer contents are aligned center in the original page,

![image](https://user-images.githubusercontent.com/60184961/91895947-c0b17800-eca0-11ea-8e2b-ed81bce59c7b.png)

 But in your project, they are not aligned center.

![image](https://user-images.githubusercontent.com/60184961/92009945-dfbc1280-ed51-11ea-99f7-c3e1195ac250.png)

- [ ] You have failed checks, please fix them. 

![image](https://user-images.githubusercontent.com/60184961/92010445-80123700-ed52-11ea-8e49-19eab944dfa2.png)


Please kindly center them.


##

**NOTES**

- [ ] Please do not make any changes to your repo after you request a code review.

##

**SUMMARY**

As I mentioned above, your project is almost done. You have some minor issues to solve. Please be an optimist and do not forget that the main purpose is to learn and practice. Do not let the requested changes discourage you 👍

##

*Kindly make the changes and submit another code review when you are ready*

Questions or comments? Reach me on [Twitter](https://twitter.com/safaerden) or [LinkedIn](https://www.linkedin.com/in/safaerden/)

Happy coding_ 👨‍💻 

**Safa ERDEN**

2020-09-03 09:02 UTC, kitpao requested changes
# 👋 Hello @Rayan84 and @dibdas 

⭐ Great job fixing most of the required and optional changes from the previous TSE 👏 
You are only missing 2 mandatory fixes, kindly check them below ⬇️ 

**_Note:_** All the **[OPTIONAL]** are **not required** in order to approve your project but are personal suggestions to improve your coding experience

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-09-03 09:02 UTC, kitpao commented on CSS/stylesheet.css
> +}
- [x] About the basic CSS bad practices, one of them is that you should not repeat the same rule. (You are repeating things like `color: white;`, `text-decoration: none;`, `display: flex;`, `border: solid 1px white;`, etc) Follow the DRY (Don't repeat yourself) rule.
![image](https://user-images.githubusercontent.com/53256139/89356769-33203f80-d684-11ea-8a2b-7776e5a73811.png)


  👉 Here you have an explanation of how you can implement it:

  You can use multiple classes for any HTML element, so for example,

  If you use these lines in many classes:
  ```
  color: #fff;
  background-color: #000;
  ```
  and you use it for .class1, .class2, and .class3 
  you can put them inside a single class called for example "common-class" so it will look like this:
  **CSS**
  ```
  .class1 {
    font-size: 24px;
  }
  .class2 {
    font-size: 30px;
  }
  .class3 {
    font-size: 10px;
  }
  .common-class {
    color: #fff;
    background-color: #000
  }
  ```
  and in **HTML**:
  ```
  <nav class="class1 common-class">  <!-- this will have font size of 24px, color of #fff and background-color of #000 -->
  ...
  <div class="class2 common-class">  <!-- this will have font size of 30px, color of #fff and background-color of #000 -->
  ...
  <footer class="class3 common-class">   <!-- this will have font size of 10px, color of #fff and background-color of #000 -->
  ...
  ```

2020-09-03 09:02 UTC, kitpao commented on README.md
> +# [Screenshot]
- [x] **OPTIONAL** It is not necessary that you add # [Screenshot], you can remove this title

2020-09-03 09:02 UTC, kitpao commented on README.md
> +* Twitter:[@Rayan65096267]https://twitter.com/Rayan65096267
- [x] The reason your links in the Twitter are not showing correctly is that you are missing to  use this format: `[text to display](link_in_parenthesis)`, please fix them

2020-09-03 11:15 UTC, expjazz approved these changes
## Status: Project Approved :clap: 

Great Work on this project, and on the changes requested by the previous TSE's.

You can go ahead on to the next projects.

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-09-03 12:44 UTC, merged